### ISSUE TITLE
Improve flow for determining whether issue is about access request

### ISSUE THREAD

**Issue by pglevy** [Bixal/complaint-screener#24]

**Comment by bnaolu** [comment]
From team discussion Tuesday (6/15)
-  Leave question order the same; instead merge Q2 to Q3:
   - New Q3: Is your complaint about a violation? > What is your complaint about? (i.e. violation or gaining access)
   - Q2 as an option to choose from (i.e. Does your complaint concern a request you made more than 30 days ago to access your health information?)
